// ---------------------------------------------------------------------------
// TypeScript mirrors of what the backend actually returns.
//
// HAND-WRITTEN FROM THE ROUTE FILES, NOT SHARED FROM THE BACKEND. The obvious
// alternative — importing the engine's own exported types, or generating these
// from the Prisma client — would couple the frontend to the backend's internals
// and, more practically, would need a monorepo or a build step this project does
// not have. Written out by hand, these types are a CONTRACT: they describe the
// JSON on the wire, which is the only thing the browser can actually see.
//
// The cost, stated: they can drift from the backend silently. A field renamed in
// Express would compile fine here and arrive as `undefined` at runtime. That is
// mitigated by the fact that every one of these was copied from the route file
// that produces it, with the source noted, so the check is a two-file diff
// rather than an investigation.
// ---------------------------------------------------------------------------

export type Provider = "CODEFORCES" | "LEETCODE";
export type SyncStatus = "PENDING" | "SYNCING" | "COMPLETED" | "FAILED";
export type DifficultyBand = "EASY" | "MEDIUM" | "HARD";

// src/routes/auth.ts — PUBLIC_USER_FIELDS. The password hash is never selected
// from the database at all, so there is no field here to accidentally render.
export type User = {
  id: string;
  email: string;
  name: string;
  createdAt: string;
};

// ---------------------------------------------------------------------------
// MASTERY — src/engine/mastery.ts, getMasteryOverview
//
// THE MOST IMPORTANT TYPE DISTINCTION IN THIS FILE, and it is deliberately
// enforced by the type system rather than by discipline:
//
//   TopicMasteryView  has a masteryScore
//   UnknownTopicView  DOES NOT HAVE ONE, and there is no optional field to fill
//
// A topic with no data is not a topic scored zero. Because `UnknownTopicView`
// simply has no `masteryScore` property, a component cannot render one for an
// unknown topic even by accident — `topic.masteryScore` is a compile error, not
// a runtime `undefined` that quietly formats as "0.0000". The backend keeps
// these in two separate arrays for exactly this reason; keeping them as two
// separate TYPES is how that intent survives into the interface.
// ---------------------------------------------------------------------------
export type TopicMasteryView = {
  topicId: string;
  name: string;
  slug: string;
  solvedCount: number;
  attemptedCount: number;
  masteryScore: number;
  targetBand: DifficultyBand;
};

export type UnknownTopicView = {
  topicId: string;
  name: string;
  slug: string;
};

export type MasteryOverview = {
  weak: TopicMasteryView[];
  strong: TopicMasteryView[];
  unknown: UnknownTopicView[];
};

// ---------------------------------------------------------------------------
// RECOMMENDATIONS — src/engine/recommend.ts, type Recommendation
// ---------------------------------------------------------------------------
export type Recommendation = {
  problemId: string;
  title: string;
  url: string;
  provider: Provider;
  // TWO COLUMNS, TWO AUDIENCES (architecture.md 2.2). `difficultyRaw` is the
  // provider's own value and is the ONLY one this app ever displays ("1600",
  // "Medium"). `difficultyBand` is the engine's normalisation and is used here
  // only to pick a colour. The UI never reads the band for display; the engine
  // never reads raw. Honouring that split is why both are on this type.
  difficultyRaw: string;
  difficultyBand: DifficultyBand;
  topics: string[];
  // Machine-generated by the engine, one of exactly six shapes:
  //   "due for revision" | "weak in <Topic>" | "unfinished attempt in <Topic>"
  //   | "unfinished attempt" | "new topic: <Topic>" | "starting point: <Topic>"
  // Always shown, never hidden behind a tooltip — auditability is the engine's
  // entire pitch.
  reason: string;
};

// ---------------------------------------------------------------------------
// REVISION — src/engine/revision.ts, getDueRevisions
// Prisma returns the whole RevisionItem row with `problem` included.
// ---------------------------------------------------------------------------
export type RevisionProblem = {
  id: string;
  title: string;
  url: string;
  provider: Provider;
  difficultyRaw: string;
  difficultyBand: DifficultyBand;
  problemTopics: { topic: { name: string } }[];
};

export type RevisionItem = {
  id: string;
  userId: string;
  problemId: string;
  dueAt: string;
  intervalDays: number;
  repetitionCount: number;
  lastReviewedAt: string | null;
  problem: RevisionProblem;
};

// POST /api/revision/:problemId/review returns the updated item, whose
// `problem` include omits problemTopics — hence the Omit rather than a reuse.
export type ReviewedItem = Omit<RevisionItem, "problem" | "userId"> & {
  problem: Omit<RevisionProblem, "problemTopics">;
};

// ---------------------------------------------------------------------------
// INTEGRATIONS — src/routes/{codeforces,leetcode}.ts
// Both providers expose the same four shapes, deliberately.
// ---------------------------------------------------------------------------
export type IntegrationStatus = {
  handle: string;
  syncStatus: SyncStatus;
  lastSyncedAt: string | null;
};

export type LinkedAccount = {
  id: string;
  provider: Provider;
  handle: string;
  syncStatus: SyncStatus;
  lastSyncedAt: string | null;
  createdAt: string;
};

// POST /sync returns `{ handle, ...counts }`, and the two providers report
// DIFFERENT counts (Codeforces has ratingChangesCreated, LeetCode has
// gapLookups, and so on). Rather than model two count shapes we will never
// display individually, the fields this app actually shows are named and the
// rest are left as an index signature. Nothing here is invented.
export type SyncResult = {
  handle: string;
  solved?: number;
  userProblemsCreated?: number;
  userProblemsUpdated?: number;
  topicsUpdated?: number;
  revisionItemsCreated?: number;
  problemsCreated?: number;
  durationMs?: number;
  [key: string]: unknown;
};
